- name: Gather and print Ansible facts
  hosts: localhost
  # gather_facts: no
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
    
    - name: Print all facts
      ansible.builtin.debug:
        var: ansible_facts
